from __future__ import annotations

import json
import os
from pathlib import Path
import re
import urllib.error
import urllib.request

from gen_issue_draft import _parse_fields, _parse_sections, _run_command
from body_contract import issue_body_context_line_bounds


DEFAULT_GITHUB_MODELS_ENDPOINT = "https://models.github.ai/inference/chat/completions"
DEFAULT_GITHUB_API_VERSION = "2026-03-10"
DEFAULT_CONTEXT_MODEL = "openai/gpt-4.1-mini"
JSON_BLOCK_RE = re.compile(r"\{.*\}", re.DOTALL)
SENTENCE_SPLIT_RE = re.compile(r"(?<=[.!?])\s+(?=[A-Z0-9\"'`(])")


def _coerce_endpoint(base_or_endpoint: str | None) -> str:
    raw = (base_or_endpoint or "").strip()
    if raw:
        if raw.endswith("/chat/completions"):
            return raw
        return raw.rstrip("/") + "/chat/completions"
    return DEFAULT_GITHUB_MODELS_ENDPOINT


def _resolve_api_key() -> str | None:
    for env_name in ["ISSUE_CONTEXT_LLM_API_KEY", "OPENAI_API_KEY", "GITHUB_TOKEN", "GH_TOKEN"]:
        value = (os.getenv(env_name) or "").strip()
        if value:
            return value

    gh_auth = _run_command(["gh", "auth", "token"])
    token = gh_auth.stdout.strip()
    if gh_auth.returncode == 0 and token:
        return token
    return None


def _resolve_endpoint() -> str:
    explicit_endpoint = (os.getenv("ISSUE_CONTEXT_LLM_ENDPOINT") or "").strip()
    if explicit_endpoint:
        return _coerce_endpoint(explicit_endpoint)

    explicit_base = (os.getenv("ISSUE_CONTEXT_LLM_BASE_URL") or os.getenv("OPENAI_BASE_URL") or "").strip()
    if explicit_base:
        return _coerce_endpoint(explicit_base)

    return DEFAULT_GITHUB_MODELS_ENDPOINT


def _resolve_model() -> str:
    return (os.getenv("ISSUE_CONTEXT_LLM_MODEL") or os.getenv("OPENAI_MODEL") or DEFAULT_CONTEXT_MODEL).strip()


def _context_target_count(source_log_text: str) -> int:
    _, max_count = issue_body_context_line_bounds(source_log_text)
    return max_count


def _render_grounding_text(source_log_text: str, merged_pr_numbers: list[int] | None) -> str:
    fields = _parse_fields(source_log_text)
    sections = _parse_sections(source_log_text)
    merged_pr_text = ", ".join(f"#{number}" for number in merged_pr_numbers or []) or "none"

    lines = [
        f"id: {fields.get('id', '')}",
        f"title: {fields.get('title', '')}",
        f"scope: {fields.get('scope', '')}",
        f"tags: {fields.get('tags', '')}",
        f"issue_keyword: {fields.get('issue_keyword', '')}",
        f"parent_log: {fields.get('parent_log', '')}",
        f"previous_log: {fields.get('previous_log', '')}",
        f"merged_prs: {merged_pr_text}",
        "",
    ]

    section_names = [
        "Decision / Outcome",
        "PR Summary Inputs (optional)",
        "Scope",
        "Success Criteria (DoD)",
        "Success Criteria",
        "Current Status",
        "Recent changes (for traceability, optional)",
        "Recent changes",
    ]
    for section_name in section_names:
        section_lines = sections.get(section_name) or []
        bullet_lines: list[str] = []
        for raw in section_lines:
            stripped = raw.strip()
            if stripped.startswith("- "):
                bullet_lines.append(stripped)
            if len(bullet_lines) >= 6:
                break
        if bullet_lines:
            lines.append(f"## {section_name}")
            lines.extend(bullet_lines)
            lines.append("")

    return "\n".join(lines).strip()


def _build_messages(source_log_text: str, merged_pr_numbers: list[int] | None) -> list[dict[str, str]]:
    target_count = _context_target_count(source_log_text)
    issue_scope = "top-level parent issue" if target_count == 5 else "child issue"
    grounding_text = _render_grounding_text(source_log_text, merged_pr_numbers)

    system_prompt = (
        "You write GitHub issue Context sections from one source log. "
        "Write naturally like a human summarizing the issue. "
        "Do not force carry-forward, baseline, future follow-up, or ledger phrasing. "
        "Return JSON only with one key named lines whose value is an array of sentences."
    )
    user_prompt = (
        f"Write the Context block for one {issue_scope}.\n"
        f"Requirements:\n"
        f"- Return exactly {target_count} sentences in JSON as {{\"lines\": [\"...\"]}}.\n"
        "- Each line must be one complete English sentence without bullet markers.\n"
        "- Ground every sentence in the source log and merged PR evidence when provided.\n"
        "- Do not use placeholders.\n"
        "- Do not mention that the text was generated by a model.\n"
        "- Do not force a fixed rhetorical pattern like carry-forward, future-facing closure, or reusable-baseline wording.\n"
        "- Prefer concise, concrete issue Context rather than meta commentary.\n\n"
        "Source log grounding:\n"
        f"{grounding_text}\n"
    )
    return [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": user_prompt},
    ]


def _request_headers(endpoint: str, api_key: str) -> dict[str, str]:
    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json",
        "Accept": "application/json",
    }
    if "models.github.ai" in endpoint:
        headers["Accept"] = "application/vnd.github+json"
        headers["X-GitHub-Api-Version"] = DEFAULT_GITHUB_API_VERSION
    return headers


def _extract_content(response_payload: dict) -> str:
    choices = response_payload.get("choices")
    if not isinstance(choices, list) or not choices:
        raise SystemExit("LLM Context generation failed: response contained no choices")
    message = choices[0].get("message") if isinstance(choices[0], dict) else None
    content = message.get("content") if isinstance(message, dict) else None
    if isinstance(content, str) and content.strip():
        return content.strip()
    raise SystemExit("LLM Context generation failed: response contained no assistant content")


def _extract_json_object(raw_text: str) -> dict:
    stripped = raw_text.strip()
    try:
        return json.loads(stripped)
    except json.JSONDecodeError:
        match = JSON_BLOCK_RE.search(stripped)
        if match:
            try:
                return json.loads(match.group(0))
            except json.JSONDecodeError as exc:
                raise SystemExit(f"LLM Context generation failed: assistant content was not valid JSON: {exc}") from exc
        raise SystemExit("LLM Context generation failed: assistant content was not valid JSON")


def _normalize_lines(payload: dict, target_count: int) -> list[str]:
    raw_lines = payload.get("lines")
    if not isinstance(raw_lines, list):
        raise SystemExit("LLM Context generation failed: JSON payload must contain a lines array")

    def _coerce_bullet_lines(values: list[object]) -> list[str]:
        lines: list[str] = []
        for raw in values:
            text = str(raw).strip()
            if not text:
                continue
            if text.startswith("- "):
                text = text[2:].strip()
            lines.append(f"- {text}")
        return lines

    def _split_sentence_lines(values: list[object]) -> list[str]:
        collapsed = " ".join(str(raw).strip() for raw in values if str(raw).strip())
        if not collapsed:
            return []
        if collapsed.startswith("- "):
            collapsed = collapsed[2:].strip()
        parts = [part.strip() for part in SENTENCE_SPLIT_RE.split(collapsed) if part.strip()]
        return [f"- {part}" for part in parts]

    lines = _coerce_bullet_lines(raw_lines)
    if len(lines) != target_count:
        split_lines = _split_sentence_lines(raw_lines)
        if len(split_lines) == target_count:
            lines = split_lines

    if len(lines) != target_count:
        raise SystemExit(f"LLM Context generation failed: expected exactly {target_count} lines but received {len(lines)}")
    return lines


def generate_issue_context_lines_with_llm(source_log_text: str, merged_pr_numbers: list[int] | None = None) -> list[str]:
    api_key = _resolve_api_key()
    if not api_key:
        raise SystemExit(
            "LLM Context generation requires ISSUE_CONTEXT_LLM_API_KEY, OPENAI_API_KEY, GITHUB_TOKEN, GH_TOKEN, or a valid gh auth token with models access"
        )

    endpoint = _resolve_endpoint()
    model = _resolve_model()
    payload = {
        "model": model,
        "messages": _build_messages(source_log_text, merged_pr_numbers),
        "max_completion_tokens": 600,
        "stream": False,
    }

    request = urllib.request.Request(
        endpoint,
        data=json.dumps(payload).encode("utf-8"),
        headers=_request_headers(endpoint, api_key),
        method="POST",
    )
    try:
        with urllib.request.urlopen(request, timeout=60) as response:
            response_payload = json.loads(response.read().decode("utf-8"))
    except urllib.error.HTTPError as exc:
        detail = exc.read().decode("utf-8", errors="replace")
        raise SystemExit(f"LLM Context generation request failed: HTTP {exc.code}: {detail}") from exc
    except urllib.error.URLError as exc:
        raise SystemExit(f"LLM Context generation request failed: {exc.reason}") from exc
    except json.JSONDecodeError as exc:
        raise SystemExit(f"LLM Context generation failed: response JSON could not be parsed: {exc}") from exc

    content = _extract_content(response_payload)
    json_payload = _extract_json_object(content)
    return _normalize_lines(json_payload, _context_target_count(source_log_text))