"""
Security utilities - JWT, password hashing, authentication

Provides:
- JWT token creation and verification
- Password hashing utilities
- Current user dependency injection
"""

from datetime import datetime, timedelta, timezone
from typing import Optional, Tuple
from uuid import UUID, uuid4
import jwt
from .setting import get_settings

from fastapi import Depends, HTTPException, Request, status
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from api.app.shared.actor import Actor
from api.app.shared.auth_context import AuthContext
from api.app.shared.deps import get_db
from api.app.shared.request_context import with_actor_id

from infra.database.models.library_models import LibraryModel
from infra.storage.library_membership_repository_impl import (
    SQLAlchemyLibraryMembershipRepository,
)


class SecurityConfig:
    """Centralized security configuration"""

    @staticmethod
    def create_access_token(data: dict, expires_delta: Optional[timedelta] = None) -> str:
        """
        Create JWT access token

        Args:
            data: Claims to encode in token
            expires_delta: Optional custom expiration time

        Returns:
            str: Encoded JWT token
        """
        settings = get_settings()
        to_encode = data.copy()

        if expires_delta:
            expire = datetime.now(timezone.utc) + expires_delta
        else:
            expire = datetime.now(timezone.utc) + timedelta(
                minutes=settings.access_token_expire_minutes
            )

        to_encode.update({"exp": expire})
        encoded_jwt = jwt.encode(
            to_encode,
            settings.secret_key,
            algorithm=settings.algorithm,
        )
        return encoded_jwt

    @staticmethod
    def verify_token(token: str) -> Optional[dict]:
        """
        Verify JWT token validity

        Args:
            token: JWT token string

        Returns:
            dict: Decoded payload if valid, None if invalid
        """
        settings = get_settings()
        try:
            payload = jwt.decode(
                token,
                settings.secret_key,
                algorithms=[settings.algorithm],
            )
            return payload
        except jwt.InvalidTokenError:
            return None


def _extract_bearer_token(request: Request) -> Optional[str]:
    raw = (request.headers.get("Authorization") or "").strip()
    if not raw:
        return None
    parts = raw.split(" ", 1)
    if len(parts) != 2:
        return None
    scheme, token = parts[0].strip(), parts[1].strip()
    if scheme.lower() != "bearer" or not token:
        return None
    return token


def _parse_roles(payload: dict) -> Tuple[str, ...]:
    roles = payload.get("roles")
    if not roles:
        return tuple()
    if isinstance(roles, str):
        return (roles,)
    if isinstance(roles, (list, tuple)):
        return tuple(str(r) for r in roles if r)
    return tuple()


def _parse_user_id(payload: dict) -> UUID:
    raw = payload.get("user_id") or payload.get("sub")
    if not raw:
        raise ValueError("missing user_id")
    return UUID(str(raw))


def _parse_tenant_id(request: Request) -> UUID:
    # v1 contract: tenant_id == library_id
    raw = (request.headers.get("X-Library-Id") or request.headers.get("X-Tenant-Id") or "").strip()
    if not raw:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Missing tenant header: X-Library-Id",
        )
    try:
        return UUID(raw)
    except Exception as exc:  # noqa: BLE001
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Invalid tenant header: X-Library-Id",
        ) from exc


async def get_auth_context(
    request: Request,
    db: AsyncSession = Depends(get_db),
) -> AuthContext:
    """Route C baseline dependency: returns unified AuthContext.

    - Auth: JWT Bearer token (Authorization: Bearer <token>)
    - Dev fallback: allow missing token by using DEV_USER_ID/default
    - Tenant: X-Library-Id header (tenant_id == library_id)
    - Request id: X-Request-Id header or generated by middleware
    """

    request_id = getattr(request.state, "correlation_id", None) or (
        (request.headers.get("X-Request-Id") or "").strip() or str(uuid4())
    )

    token = _extract_bearer_token(request)
    if token:
        payload = SecurityConfig.verify_token(token)
        if not payload:
            raise HTTPException(
                status_code=status.HTTP_401_UNAUTHORIZED,
                detail="Invalid token",
                headers={"WWW-Authenticate": "Bearer"},
            )
        try:
            user_id = _parse_user_id(payload)
        except Exception as exc:  # noqa: BLE001
            raise HTTPException(
                status_code=status.HTTP_401_UNAUTHORIZED,
                detail="Invalid token payload",
                headers={"WWW-Authenticate": "Bearer"},
            ) from exc
        token_roles = _parse_roles(payload)
    else:
        user_id = await get_current_user_id()
        token_roles = tuple()

    tenant_id = _parse_tenant_id(request)

    # Roles (S5A-2A): membership SoT for the selected tenant.
    # Transitional fallback: treat `libraries.user_id` as implicit owner when
    # membership rows are not present yet.
    roles: Tuple[str, ...] = tuple()
    try:
        membership_repo = SQLAlchemyLibraryMembershipRepository(db)
        role = await membership_repo.get_role(library_id=tenant_id, user_id=user_id)
        if not role:
            owner_id_result = await db.execute(
                select(LibraryModel.user_id).where(
                    LibraryModel.id == tenant_id,
                    LibraryModel.soft_deleted_at.is_(None),
                )
            )
            owner_id = owner_id_result.scalar_one_or_none()
            if owner_id == user_id:
                role = "owner"

        if role:
            normalized = str(role).strip().lower()
            if normalized == "owner":
                roles = ("owner", "admin", "member")
            elif normalized == "admin":
                roles = ("admin", "member")
            elif normalized == "member":
                roles = ("member",)
            else:
                roles = tuple()
        else:
            roles = token_roles
    except Exception:
        # Best-effort: keep requests working during local dev if DB is down.
        roles = token_roles

    with_actor_id(user_id)
    ctx = AuthContext(user_id=user_id, tenant_id=tenant_id, roles=roles, request_id=request_id)
    request.state.auth_context = ctx
    return ctx


async def get_auth_context_strict(
    request: Request,
    db: AsyncSession = Depends(get_db),
) -> AuthContext:
    """Strict AuthContext dependency for security-sensitive surfaces (e.g. search).

    Differences from get_auth_context:
    - Requires a valid JWT bearer token; missing token → 401 (no dev fallback).
    - Keeps the same tenant and role resolution semantics.
    """

    request_id = getattr(request.state, "correlation_id", None) or (
        (request.headers.get("X-Request-Id") or "").strip() or str(uuid4())
    )

    token = _extract_bearer_token(request)
    if not token:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Missing token",
            headers={"WWW-Authenticate": "Bearer"},
        )

    payload = SecurityConfig.verify_token(token)
    if not payload:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid token",
            headers={"WWW-Authenticate": "Bearer"},
        )
    try:
        user_id = _parse_user_id(payload)
    except Exception as exc:  # noqa: BLE001
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid token payload",
            headers={"WWW-Authenticate": "Bearer"},
        ) from exc
    token_roles = _parse_roles(payload)

    tenant_id = _parse_tenant_id(request)

    roles: Tuple[str, ...] = tuple()
    try:
        membership_repo = SQLAlchemyLibraryMembershipRepository(db)
        role = await membership_repo.get_role(library_id=tenant_id, user_id=user_id)
        if not role:
            owner_id_result = await db.execute(
                select(LibraryModel.user_id).where(
                    LibraryModel.id == tenant_id,
                    LibraryModel.soft_deleted_at.is_(None),
                )
            )
            owner_id = owner_id_result.scalar_one_or_none()
            if owner_id == user_id:
                role = "owner"

        if role:
            normalized = str(role).strip().lower()
            if normalized == "owner":
                roles = ("owner", "admin", "member")
            elif normalized == "admin":
                roles = ("admin", "member")
            elif normalized == "member":
                roles = ("member",)
            else:
                roles = tuple()
        else:
            roles = token_roles
    except Exception:
        roles = token_roles

    with_actor_id(user_id)
    ctx = AuthContext(user_id=user_id, tenant_id=tenant_id, roles=roles, request_id=request_id)
    request.state.auth_context = ctx
    return ctx


async def get_current_user_id() -> UUID:
    """开发环境当前用户 ID 依赖。

    之前写死为固定 UUID 导致：数据库里已有的库都是另外的 user_id → /libraries 按用户过滤结果为空。

    改进：
    1. 支持通过环境变量 DEV_USER_ID 覆盖。
       在 WSL2 或 Windows 设置后端进程环境：
         Linux/WSL2: `export DEV_USER_ID=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx`
         Windows PowerShell: `$env:DEV_USER_ID="xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"`
    2. 若未设置则回退到原始固定测试 UUID。
    3. 保留后续 TODO（JWT 解析）。
    """
    import os
    override = os.getenv("DEV_USER_ID")
    if override:
        try:
            return UUID(override)
        except Exception:
            # 环境变量格式不合法时仍使用默认测试 ID，避免启动失败
            pass
    return UUID("550e8400-e29b-41d4-a716-446655440000")


async def get_current_actor() -> Actor:
    """当前请求的 Actor（认证后的身份载体）。

    目前仍处于开发模式：只提供 user_id。
    后续接入 JWT 后，这里会解析 token 并填充 workspace_id/roles 等。
    """

    user_id = await get_current_user_id()
    with_actor_id(user_id)
    return Actor(user_id=user_id)
