# WordloomToolkit 默认配置（可随程序发布）
project_root: ""   # 若留空，默认取程序上级目录
tree:
  out_file: "TREE.md"
  ignore: [".git", "__pycache__", ".venv", "node_modules", "dist", "build"]
fix_path:
  prefix: "../static"
  exts: [".md"]
  asset_exts: [".png", ".jpg", ".jpeg", ".gif", ".mp4", ".webm", ".svg"]
  backup: true
  dry_run: false
gif:
  ffmpeg_path: "auto"
  gif_dir: "assets/static/media/gif"
  thumb_dir: "assets/static/media/thumb"
  make_thumbnail: true
  thumbnail_ext: ".jpg"
  default_duration: 8
  default_fps: 8
  default_width: 640
