# 你的个性化设置（运行时生成/可手改）；同键会覆盖 default.yaml
project_root: "D:\\Project\\Wordloom"
gif_dir: "assets/static/media/gif"
thumb_dir: "assets/static/media/thumb"
video_dir: "assets/static/media/video"
img_dir: "assets/static/media/img"


# nested gif config for Toolkit
gif:
  streamlit_path: "WordloomFrontend/streamlit/gif_maker.py"
  gif_dir: "assets/static/media/gif"
  thumb_dir: "assets/static/media/thumb"
